// RZ—02 edit plan (Director). Contract: projects/reze2/CONTEXT.md.
// Every boundary sits on the beat / half-beat grid. B(n) is beat n with the
// same numbering as work/beats.txt (bars start at beats 1, 5, 9, …; the drop is
// B(89) = 31.14 s). B(n) = 0.62 + 0.3468·(n−1), so B(4i+1) = b(i).
//
// Optional, safe-to-ignore extensions (see BRIEF.md):
//   bg   (clip)  'white' | 'black'  — what surrounds strips / stacks
//   tone (3d)    'pearl' | 'silver' | 'electric' | 'prism'  — 3D colourway
// Source windows: clean 0–38.8, church 0–83.7 (use band uv.y 0.13–0.86),
// fireworks 0–78 (use uv.y ≥ 0.1).

const B = (n) => Math.round((0.62 + 0.3468 * (n - 1)) * 1e4) / 1e4;
const c = (from, fx = 0.5) => ({ src: 'clean', from, fx });
const ch = (from, fx = 0.5) => ({ src: 'church', from, fx });
const fw = (from, fx = 0.5) => ({ src: 'fireworks', from, fx });

export default [
  // ── OPEN ───────────────────────────────────────────────── 0 – 2.01
  { start: 0, end: B(1), kind: 'black', in: 'cut',
    note: 'pickup note plays into pure black, like the reference opening' },
  { start: B(1), end: B(5), kind: '3d', scene: 'ribbons', tone: 'pearl', in: 'cut',
    note: 'bar 0: glass/chrome ribbons unfurl on white — the abstract language is stated before any character appears' },

  // ── RAIN (white paper, strips) ─────────────────────────── 2.01 – 6.17
  { start: B(5), end: B(7), kind: 'clip', layout: 'stack2', shots: [c(0.4, 0.5), c(2.5, 0.35)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .71 — first footage: rain street on top, her smile below; the story in one frame' },
  { start: B(7), end: B(8), kind: 'clip', layout: 'strip', shots: [c(2.9, 0.35)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .68 — head lifts into the smile' },
  { start: B(8), end: B(9), kind: 'clip', layout: 'strip', shots: [c(5.8, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .51 — the flower enters frame' },
  { start: B(9), end: B(11), kind: 'clip', layout: 'glass', shots: [c(6.7, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'loudness dips (.50) — the flower bite (mouth opens 6.8–7.3) on a slowly turning glass pane' },
  { start: B(11), end: B(13), kind: 'clip', layout: 'stack3', shots: [c(0.9, 0.5), c(3.6, 0.35), c(9.2, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'rain / smile / doorway triptych — rhythm through layout, not effects' },
  { start: B(13), end: B(15), kind: 'clip', layout: 'strip', shots: [c(13.25, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'bar-3 hit .65 — she points straight at the lens (13.3–13.6)' },
  { start: B(15), end: B(17), kind: 'clip', layout: 'stack2', shots: [c(14.25, 0.4), c(10.0, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'the wave over the doorway — phrase 1 closes' },

  // ── DOOR / FLOWER spam run ─────────────────────────────── 6.17 – 11.72
  { start: B(17), end: B(19), kind: '3d', scene: 'orbit', tone: 'pearl', in: 'cut',
    note: 'soft bar-4 downbeat (.48): thin light-blue arcs orbit on white (ref 0:05.3)' },
  { start: B(19), end: B(21), kind: 'clip', layout: 'strip', shots: [c(8.6, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'at the door — hold 2 beats so the face reads before the spam run' },
  { start: B(21), end: B(22), kind: 'clip', layout: 'stack2', shots: [c(2.6, 0.35), c(13.3, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'bar-5 hit run (.58 .50 .77 .54 .74) starts: one cut per beat' },
  { start: B(22), end: B(23), kind: 'clip', layout: 'stack2', shots: [c(6.9, 0.45), c(10.4, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'flower / door, swapped rows' },
  { start: B(23), end: B(24), kind: 'clip', layout: 'strip', shots: [c(13.32, 0.45)], look: 'natural', stutter: 0.5, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .77 — the point, fired twice per beat' },
  { start: B(24), end: B(25), kind: 'clip', layout: 'stack3', shots: [c(3.0, 0.35), c(7.0, 0.45), c(14.3, 0.4)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'smile / bite / wave — three moments in one beat' },
  { start: B(25), end: B(26), kind: 'clip', layout: 'full', shots: [fw(14.56, 0.4)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'flash',
    note: 'hit .74 — a single prismatic star from the fireworks reel, a tease of the drop (dark + abstract, so full-frame is fine for 1 beat)' },
  { start: B(26), end: B(29), kind: 'clip', layout: 'strip', shots: [c(12.9, 0.45)], look: 'natural', stutter: 0, speed: 0.5, bg: 'white', in: 'cut',
    note: 'beat 26 has zero onset — the spin toward camera at 0.5×, pure elegance after the run' },
  { start: B(29), end: B(31), kind: 'clip', layout: 'stack2', shots: [c(9.4, 0.3), c(4.2, 0.35)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hits .63/.50 — doorway over smile' },
  { start: B(31), end: B(33), kind: 'clip', layout: 'strip', shots: [ch(10.2, 0.5)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'moonlit blue classroom — night enters; first black background' },

  // ── CHROME / NIGHT ─────────────────────────────────────── 11.72 – 15.88
  { start: B(33), end: B(37), kind: '3d', scene: 'kaleido', tone: 'silver', in: 'cut',
    note: 'bar 8: silver chrome mandala on black (ref 0:01.3 / 0:04.7) — the "abstract" thesis, one full bar' },
  { start: B(37), end: B(39), kind: 'clip', layout: 'stack3', shots: [ch(11.0), ch(22.5), ch(76.0)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .66 — school-at-night triptych: desks, hall, lit library window (subtitle band cropped away by the strips)' },
  { start: B(39), end: B(40), kind: 'clip', layout: 'strip', shots: [ch(1.0, 0.45)], look: 'mono', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .59 — her grey portrait, paper texture intact' },
  { start: B(40), end: B(41), kind: 'black', in: 'cut',
    note: 'loudness dips to .48 — 1 beat of pure black before the biggest build hit' },
  { start: B(41), end: B(43), kind: '3d', scene: 'shards', tone: 'electric', in: 'flash',
    note: 'hit .88 — crystal-shard burst in electric blue (ref 0:09–0:10)' },
  { start: B(43), end: B(45), kind: 'clip', layout: 'strip', shots: [fw(11.82, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'figure inside the blue vortex — on-palette fireworks, readable at strip size' },

  // ── CAFÉ ───────────────────────────────────────────────── 15.88 – 22.82
  { start: B(45), end: B(47), kind: 'clip', layout: 'strip', shots: [c(16.3, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'café counter wide — back to daylight and white paper' },
  { start: B(47), end: B(49), kind: 'clip', layout: 'stack2', shots: [c(18.4, 0.55), c(20.6, 0.42)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'counter over hand-at-collar' },
  { start: B(49), end: B(51), kind: '3d', scene: 'ribbons', tone: 'pearl', in: 'cut',
    note: 'hit .52 — ribbons return as punctuation between café beats' },
  { start: B(51), end: B(53), kind: 'clip', layout: 'glass', shots: [c(20.7, 0.42)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hand at her collar on a tilted glass pane' },
  { start: B(53), end: B(55), kind: 'clip', layout: 'stack2', shots: [c(22.3, 0.3), c(21.3, 0.42)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .66 — arm raised over the collar gesture' },
  { start: B(55), end: B(56), kind: 'clip', layout: 'strip', shots: [c(22.55, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .57 — arm up, beside him' },
  { start: B(56), end: B(57), kind: 'clip', layout: 'strip', shots: [c(26.5, 0.5)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .53 — finger to her eye' },
  { start: B(57), end: B(58), kind: 'clip', layout: 'strip', shots: [c(30.6, 0.45)], look: 'natural', stutter: 0.25, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .79 — first quarter-beat stutter: the high-key close-up fires 4×' },
  { start: B(58), end: B(59), kind: 'clip', layout: 'strip', shots: [c(33.0, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'smile, head tilted' },
  { start: B(59), end: B(60), kind: 'clip', layout: 'stack2', shots: [c(30.9, 0.45), fw(15.3, 0.5)], look: 'ice', stutter: 0.5, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .84 — first time her face and a (cyan) blast share a frame: foreshadows the drop' },
  { start: B(60), end: B(61), kind: 'clip', layout: 'strip', shots: [c(33.4, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'back to the smile' },
  { start: B(61), end: B(63), kind: 'clip', layout: 'strip', shots: [c(35.3, 0.55)], look: 'natural', stutter: 0, speed: 0.5, bg: 'white', in: 'cut',
    note: 'hit .71 — she looks into camera, 0.5×' },
  { start: B(63), end: B(65), kind: '3d', scene: 'orbit', tone: 'electric', in: 'cut',
    note: 'weak bar end (.15–.28): electric-blue glass tubes orbit — day turns to night' },

  // ── LAUGH / NIGHT / SKY ────────────────────────────────── 22.82 – 28.37
  { start: B(65), end: B(67), kind: 'clip', layout: 'stack2', shots: [ch(45.0), ch(12.0)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .50 — window light (cooled by ice) over the moonlit desks' },
  { start: B(67), end: B(69), kind: 'clip', layout: 'full', shots: [fw(42.3, 0.6)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'one thin laser line across the night city, iced to cyan — minimal and abstract, so full-frame upscale is invisible' },
  { start: B(69), end: B(70), kind: 'clip', layout: 'strip', shots: [c(24.3, 0.38)], look: 'natural', stutter: 0.25, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .75 — the laugh, stuttered' },
  { start: B(70), end: B(71), kind: 'clip', layout: 'strip', shots: [c(22.6, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'arm up' },
  { start: B(71), end: B(72), kind: 'clip', layout: 'stack2', shots: [c(24.6, 0.38), c(17.0, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .70 — laugh over the café' },
  { start: B(72), end: B(73), kind: 'clip', layout: 'strip', shots: [c(24.85, 0.38)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'hit .55 — the laugh continues, un-stuttered' },
  { start: B(73), end: B(74), kind: 'clip', layout: 'stack3', shots: [c(24.4, 0.38), c(2.7, 0.35), c(6.95, 0.45)], look: 'natural', stutter: 0.5, speed: 1, bg: 'white', in: 'prism',
    note: 'hit .82 — laugh / smile / bite triptych stuttering, then release' },
  { start: B(74), end: B(80), kind: '3d', scene: 'sky', tone: 'pearl', in: 'iris',
    note: 'SKY BREATHER — the lowest-onset stretch of the build (hits ≤ .46, 6 beats); the reference\'s cloud interlude' },
  { start: B(80), end: B(81), kind: '3d', scene: 'shards', tone: 'prism', in: 'flash',
    note: 'beat 80 hit = 1.00, the strongest onset in the song — the sky shatters to blown-out white' },

  // ── PRE-DROP RISER ─────────────────────────────────────── 28.37 – 31.14
  { start: B(81), end: B(83), kind: 'clip', layout: 'full', shots: [ch(80.4, 0.42)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the green-eye close-up, big, 2 beats — anchor of the riser (dark, graphic; full is acceptable here)' },
  { start: B(83), end: B(84), kind: 'clip', layout: 'strip', shots: [c(31.0, 0.45)], look: 'mono', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'her close-up in silver' },
  { start: B(84), end: B(85), kind: 'clip', layout: 'strip', shots: [ch(82.0, 0.42)], look: 'mono', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the eye again, silver' },
  { start: B(85), end: B(86), kind: 'clip', layout: 'stack2', shots: [fw(28.6, 0.45), c(24.4, 0.38)], look: 'ice', stutter: 0.5, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .68 — chainsaw sparks (iced) over the laugh' },
  { start: B(86), end: B(86.5), kind: 'clip', layout: 'strip', shots: [fw(14.56, 0.4)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'half-beat cuts: acceleration — the star' },
  { start: B(86.5), end: B(87), kind: 'clip', layout: 'strip', shots: [fw(10.9)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'half-beat — the blue flower' },
  { start: B(87), end: B(88), kind: 'clip', layout: 'strip', shots: [ch(82.6, 0.42)], look: 'mono', stutter: 0.25, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .67 — the eye trembles at quarter-beats' },
  { start: B(88), end: B(89), kind: 'black', in: 'cut',
    note: 'beat 88 (.26) — pure black so the drop lands out of nothing' },

  // ── DROP A: shards + fireworks ─────────────────────────── 31.14 – 36.69
  { start: B(89), end: B(91), kind: '3d', scene: 'shards', tone: 'prism', shots: [fw(37.3, 0.45)], speed: 1, in: 'shatter',
    note: 'THE DROP (31.14): the frame shatters into prismatic crystal shards carrying the cyan blast' },
  { start: B(91), end: B(93), kind: 'clip', layout: 'kaleido', shots: [fw(10.9)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'loud .92 — the blue flower explosion folded into a mandala' },
  { start: B(93), end: B(94), kind: 'clip', layout: 'strip', shots: [fw(37.0, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'cyan starburst with the figure' },
  { start: B(94), end: B(95), kind: 'clip', layout: 'stack2', shots: [fw(28.6, 0.45), c(14.3, 0.4)], look: 'ice', stutter: 0.25, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .60 — sparks over her wave, quarter-beat spam' },
  { start: B(95), end: B(97), kind: '3d', scene: 'kaleido', tone: 'electric', in: 'cut',
    note: 'beat 95 is the loudest moment (1.00) — electric-blue chrome mandala' },
  { start: B(97), end: B(98), kind: 'clip', layout: 'strip', shots: [fw(30.5, 0.35)], look: 'invert', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'red blast inverted to cyan, silhouette turns white' },
  { start: B(98), end: B(99), kind: 'clip', layout: 'strip', shots: [fw(12.4, 0.4)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'figure diving through blue' },
  { start: B(99), end: B(101), kind: 'clip', layout: 'stack3', shots: [fw(36.3), fw(8.8), fw(15.3)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'Y2K spheres / violet blast / cyan burst — a wall of colour on the quiet beats' },
  { start: B(101), end: B(102), kind: 'clip', layout: 'full', shots: [fw(14.56, 0.4)], look: 'natural', stutter: 0.5, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .53 — the star motif, stuttered, full-frame for 1 beat' },
  { start: B(102), end: B(103), kind: 'clip', layout: 'strip', shots: [c(32.9, 0.55)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'her calm smile punches through the chaos' },
  { start: B(103), end: B(104), kind: 'clip', layout: 'stack2', shots: [fw(9.0), c(6.95, 0.45)], look: 'ice', stutter: 0.25, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .62 — blast over the flower bite' },
  { start: B(104), end: B(105), kind: '3d', scene: 'shards', tone: 'electric', in: 'cut',
    note: 'one-beat shard hit closes the first drop phrase' },

  // ── DROP B: her vs the fireworks ───────────────────────── 36.69 – 42.24
  { start: B(105), end: B(107), kind: 'clip', layout: 'stack2', shots: [c(2.6, 0.35), fw(6.1)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'prism',
    note: 'hit .79 — the date (top) vs the bomb (bottom): the film\'s story as a split' },
  { start: B(107), end: B(109), kind: 'clip', layout: 'stack2', shots: [c(13.3, 0.45), fw(37.2, 0.45)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'she points / the figure in the cyan blast' },
  { start: B(109), end: B(111), kind: '3d', scene: 'orbit', tone: 'electric', in: 'cut',
    note: 'electric orbit — breath inside the loud section' },
  { start: B(111), end: B(113), kind: 'clip', layout: 'stack3', shots: [c(30.6, 0.45), fw(44.3, 0.6), ch(11.5)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'close-up / glowing creature over the city / moonlit desks' },
  { start: B(113), end: B(115), kind: 'clip', layout: 'glass', shots: [fw(56.55)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'purple lightning creature on a glass pane — the palette\'s light purple' },
  { start: B(115), end: B(117), kind: 'clip', layout: 'strip', shots: [c(36.0, 0.55)], look: 'natural', stutter: 0, speed: 0.5, bg: 'white', in: 'cut',
    note: 'quiet beats (.17–.34): her smile at 0.5× on white — calm before .77' },
  { start: B(117), end: B(118), kind: 'clip', layout: 'full', shots: [fw(41.3)], look: 'invert', stutter: 0.25, speed: 1, bg: 'black', in: 'flash',
    note: 'hit .77 — orange blast inverted to deep blue, quarter-beat strobe' },
  { start: B(118), end: B(119), kind: 'clip', layout: 'strip', shots: [fw(45.2, 0.6)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the glowing creature over the city grid' },
  { start: B(119), end: B(120), kind: 'clip', layout: 'stack2', shots: [c(30.8, 0.45), fw(48.2, 0.45)], look: 'ice', stutter: 0.5, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .56 — close-up over the tower explosion' },
  { start: B(120), end: B(121), kind: 'clip', layout: 'strip', shots: [fw(63.8, 0.6)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'figure, blast, tower' },

  // ── DROP C: silver chapter ─────────────────────────────── 42.24 – 47.79
  { start: B(121), end: B(123), kind: '3d', scene: 'ribbons', tone: 'silver', in: 'cut',
    note: 'hit .70 — silver ribbons on black open the monochrome chapter (ref 0:04)' },
  { start: B(123), end: B(125), kind: 'clip', layout: 'strip', shots: [fw(65.8, 0.55)], look: 'chrome', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the grey creature with its glowing core' },
  { start: B(125), end: B(126), kind: 'clip', layout: 'strip', shots: [ch(1.5, 0.45)], look: 'mono', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'her grey portrait again' },
  { start: B(126), end: B(127), kind: 'clip', layout: 'stack2', shots: [fw(67.3, 0.25), fw(69.5)], look: 'mono', stutter: 0.25, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .62 — blade figure / creature, quarter-beat spam' },
  { start: B(127), end: B(129), kind: '3d', scene: 'kaleido', tone: 'silver', in: 'cut',
    note: 'loud .98 — silver mandala' },
  { start: B(129), end: B(131), kind: 'clip', layout: 'stack3', shots: [ch(45.5), c(26.6, 0.5), ch(2.2, 0.45)], look: 'mono', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'window-light streaks / finger at eye / portrait — silver triptych' },
  { start: B(131), end: B(133), kind: 'clip', layout: 'strip', shots: [c(37.0, 0.55)], look: 'mono', stutter: 0, speed: 0.5, bg: 'black', in: 'cut',
    note: 'quiet beats (.13–.15): she is silver now, 0.5×' },
  { start: B(133), end: B(134), kind: 'clip', layout: 'full', shots: [fw(72.01, 0.45)], look: 'mono', stutter: 0.25, speed: 1, bg: 'black', in: 'flash',
    note: 'hit .71 — black silhouette on white (3-frame source window, stuttered)' },
  { start: B(134), end: B(135), kind: 'clip', layout: 'strip', shots: [fw(67.6, 0.25)], look: 'chrome', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the blade in chrome' },
  { start: B(135), end: B(136), kind: 'clip', layout: 'stack2', shots: [ch(82.3, 0.42), c(24.5, 0.38)], look: 'mono', stutter: 0.25, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .63 — eye over laugh' },
  { start: B(136), end: B(137), kind: 'black', in: 'cut',
    note: 'loudness dip (.60 → .54) — phrase-end black' },

  // ── DROP D: maximum spam ───────────────────────────────── 47.79 – 53.34
  { start: B(137), end: B(139), kind: '3d', scene: 'shards', tone: 'electric', in: 'shatter',
    note: 'hit .71 — second shatter re-launches the chorus' },
  { start: B(139), end: B(140), kind: 'clip', layout: 'stack3', shots: [fw(11.9, 0.55), fw(37.25, 0.45), fw(56.6)], look: 'natural', stutter: 0.5, speed: 1, bg: 'black', in: 'cut',
    note: 'loud .92 — vortex / cyan / purple, stuttering' },
  { start: B(140), end: B(141), kind: 'clip', layout: 'strip', shots: [c(9.6, 0.3)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'the doorway, iced' },
  { start: B(141), end: B(141.5), kind: 'clip', layout: 'strip', shots: [fw(34.2)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'half-beat — fireworks lights on a wire' },
  { start: B(141.5), end: B(142), kind: 'clip', layout: 'strip', shots: [c(3.2, 0.35)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'half-beat — rain smile' },
  { start: B(142), end: B(143), kind: 'clip', layout: 'kaleido', shots: [fw(36.4)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'Y2K spheres folded into a mandala' },
  { start: B(143), end: B(145), kind: 'clip', layout: 'stack2', shots: [c(7.0, 0.45), fw(21.8)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'flower bite over the (iced) yellow explosions' },
  { start: B(145), end: B(147), kind: '3d', scene: 'orbit', tone: 'electric', in: 'cut',
    note: 'weak beats (.15–.38) — electric orbit' },
  { start: B(147), end: B(149), kind: 'clip', layout: 'strip', shots: [c(14.2, 0.4)], look: 'natural', stutter: 0, speed: 0.5, bg: 'black', in: 'cut',
    note: 'the wave, slowed — she is saying goodbye' },
  { start: B(149), end: B(150), kind: 'clip', layout: 'full', shots: [fw(1.6, 0.5)], look: 'invert', stutter: 0.25, speed: 1, bg: 'black', in: 'prism',
    note: 'hit .69 — falling figure on red, inverted to cyan' },
  { start: B(150), end: B(151), kind: 'clip', layout: 'strip', shots: [c(22.6, 0.3)], look: 'natural', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'arm up' },
  { start: B(151), end: B(152), kind: 'clip', layout: 'stack2', shots: [c(24.3, 0.38), fw(12.0, 0.55)], look: 'natural', stutter: 0.5, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .58 — laugh over the blue vortex' },
  { start: B(152), end: B(153), kind: '3d', scene: 'shards', tone: 'electric', in: 'cut',
    note: 'one-beat shard hit closes the last drop phrase (mirrors B104)' },

  // ── OUTRO: resolve to white and sky ────────────────────── 53.34 – 60
  { start: B(153), end: B(155), kind: 'clip', layout: 'kaleido', shots: [ch(81.2, 0.42)], look: 'ice', stutter: 0, speed: 1, bg: 'black', in: 'cut',
    note: 'hit .63 — the green eye becomes a mandala' },
  { start: B(155), end: B(157), kind: 'clip', layout: 'stack3', shots: [c(2.8, 0.35), c(13.3, 0.45), c(24.4, 0.38)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'recap on white: rain smile / point / laugh' },
  { start: B(157), end: B(159), kind: '3d', scene: 'ribbons', tone: 'pearl', in: 'cut',
    note: 'pearl ribbons — the opening image returns' },
  { start: B(159), end: B(161), kind: 'clip', layout: 'stack2', shots: [c(33.0, 0.55), c(5.9, 0.45)], look: 'natural', stutter: 0, speed: 1, bg: 'white', in: 'cut',
    note: 'smile over the flower — last footage pair' },
  { start: B(161), end: B(167), kind: '3d', scene: 'sky', tone: 'pearl', shots: [c(33.3, 0.55)], speed: 0.5, in: 'iris',
    note: 'RESOLVE: her smile on a glass pane drifting in the sky, 0.5×, 6 beats while the song fades' },
  { start: B(167), end: B(171), kind: '3d', scene: 'sky', tone: 'pearl', in: 'cut',
    note: 'hit .60: the pane is gone — only sky through the last bar hit (.59 at B169)' },
  { start: B(171), end: 60, kind: 'black', in: 'cut',
    note: 'cut to black, watermark stays to the last frame' },
];
