// sync.js — music timing for "Found" (Panchiko window of media/song.mp4: 176.016 → 236.706 s).
// GENERATED by work/music/make_sync.py + write_syncjs.py — do not hand-edit; ask the music editor to regenerate.
//
// ALL TIMES ARE FILM SECONDS (0 = window start = song 176.016 s). At 60 fps: frame = Math.round(t * 60).
// Tempo 87.0 BPM, 4/4, no drift (beat 0.68966 s, bar 2.7586 s). Beat grid approved by the user by ear.
//
// Drum hits: ADTOF drum transcription (github.com/xavriley/ADTOF-pytorch) run on a Demucs (htdemucs) drum stem AND on the
// full mix, onset timing refined to ~1 ms on the stem's band envelope (kick <150 Hz, snare 150 Hz–5 kHz, cymbal >6 kHz).
// Kept only if confident (model agreement or strong stem attack) and within 40 ms of the 87-BPM 16th-note grid.
// Groove found: kick on 16ths 1, 4, 9, 12, 15; snare on 5, 10, 13 (beat 2, the "e" of 3, beat 4). The drop-out
// (17.24–22.07) has NO drums. Closed hi-hat is inaudible in this mix: `hats` = crash/cymbal-wash onsets only (sparse).
// weights.* = loudness of each hit, 0.25..1 (same order as the list). Check video: out/panchiko-detail-test.mp4.

export const WINDOW = { start: 176.016, end: 236.706, duration: 60.690 };
export const BPM = 87.0;
export const BEAT = 0.68966;
export const BAR = 2.75864;
export const SIXTEENTH = BEAT / 4;

const beats = [
  0.000,0.690,1.379,2.069,2.759,3.448,4.138,4.828,5.517,6.207,6.897,7.586,
  8.276,8.966,9.655,10.345,11.035,11.724,12.414,13.104,13.793,14.483,15.173,15.862,
  16.552,17.242,17.931,18.621,19.311,20.000,20.690,21.380,22.069,22.759,23.449,24.138,
  24.828,25.518,26.207,26.897,27.587,28.276,28.966,29.656,30.345,31.035,31.724,32.414,
  33.104,33.793,34.483,35.173,35.862,36.552,37.242,37.931,38.621,39.311,40.000,40.690,
  41.380,42.069,42.759,43.449,44.138,44.828,45.518,46.207,46.897,47.587,48.276,48.966,
  49.656,50.345,51.035,51.725,52.414,53.104,53.794,54.483,55.173,55.863,56.552,57.242,
  57.932,58.621,59.311,60.001,
];          // 88 beats; bar n beat k = beats[(n-1)*4 + k-1]
const downbeats = [
  0.000,2.759,5.517,8.276,11.035,13.793,16.552,19.311,22.069,24.828,27.587,30.345,
  33.104,35.862,38.621,41.380,44.138,46.897,49.656,52.414,55.173,57.932,
];  // 22 bar starts ("1")
const kicks = [
  0.029,0.518,1.400,1.902,2.417,2.789,3.280,4.157,4.669,5.178,5.528,6.040,
  6.917,7.436,7.938,8.789,9.670,10.189,10.688,11.549,12.430,12.949,13.450,13.810,
  14.316,15.190,15.709,16.210,22.589,23.455,23.978,24.487,25.349,26.215,26.738,27.240,
  27.414,27.576,28.109,28.990,29.478,29.996,30.335,30.869,31.746,32.258,32.756,33.611,
  34.502,35.017,35.519,35.885,36.379,36.909,37.257,37.769,38.277,38.638,39.137,40.018,
  40.530,41.039,41.375,41.878,42.756,43.280,43.798,44.138,44.657,45.527,46.050,46.535,
  46.887,47.420,48.298,48.818,49.319,49.654,50.177,51.043,51.570,52.064,52.437,52.937,
  53.819,54.330,54.828,55.684,56.568,57.087,59.338,59.845,
];
const snares = [
  0.677,1.555,2.071,3.438,4.318,4.847,6.198,6.735,7.076,7.592,8.952,9.830,
  10.346,11.711,12.590,13.106,14.472,15.350,15.865,22.745,23.622,24.139,25.505,26.383,
  26.899,28.265,29.149,29.657,31.038,31.903,32.417,33.783,34.662,35.178,36.539,37.420,
  37.932,39.306,40.185,40.696,42.068,42.939,43.460,44.825,45.701,46.219,47.585,48.465,
  48.978,50.347,51.216,51.736,53.099,53.984,54.485,55.864,59.502,
];
const hats = [
  1.030,2.407,5.166,5.847,22.748,26.209,27.042,28.304,33.783,34.980,39.333,42.947,
  44.847,47.787,51.879,53.970,58.629,
];           // cymbal washes / crashes (see note above)
const toms = [
  10.679,12.596,15.872,16.199,22.745,23.451,23.627,23.967,24.140,24.477,25.155,25.333,
  25.506,25.850,26.030,26.204,26.389,26.726,26.898,27.573,29.148,33.790,34.668,35.184,
];           // almost all inside the tom fill after the slam

const weights = {
  kicks: [0.25,1.0,1.0,0.89,0.87,0.25,0.99,1.0,0.86,0.83,0.87,0.95,1.0,0.93,0.89,1.0,0.95,0.85,0.9,0.88,0.93,0.9,0.89,0.34,0.83,0.94,0.82,0.98,0.95,0.76,0.75,0.72,0.81,0.87,0.84,0.74,0.48,0.55,0.82,0.76,0.85,0.67,0.48,0.86,0.82,0.81,0.53,0.84,0.79,0.73,0.62,0.26,0.69,0.46,0.72,0.78,0.52,0.52,0.56,0.73,0.58,0.64,0.25,0.56,0.52,0.6,0.58,0.25,0.5,0.64,0.6,0.58,0.48,0.75,0.69,0.63,0.49,0.41,0.8,0.7,0.75,0.65,0.25,0.71,0.71,0.74,0.65,0.72,0.62,0.38,0.76,0.69],
  snares: [1.0,0.98,0.99,1.0,0.98,0.96,1.0,0.74,0.97,0.98,0.99,0.96,1.0,0.99,1.0,0.96,0.95,0.96,0.93,0.92,0.88,0.86,0.86,0.91,0.94,0.96,0.95,0.93,0.93,0.94,0.9,0.95,0.87,0.88,0.9,0.83,0.9,0.79,0.86,0.88,0.91,0.84,0.89,0.84,0.62,0.77,0.25,0.25,0.72,0.25,0.65,0.6,0.5,0.68,0.48,0.45,0.25],
  hats: [0.52,0.48,0.67,0.65,0.55,0.25,0.32,1.0,0.53,0.27,0.64,0.97,0.57,0.71,0.54,0.59,1.0],
  toms: [1.0,0.95,0.84,1.0,0.58,0.67,0.63,0.71,0.62,0.72,0.25,0.71,0.57,0.55,0.25,0.75,0.7,0.69,0.67,0.37,0.8,0.71,0.71,0.68],
};

// Structural accents (from the approved beat test)
const accents = [
  16.552, // last full hit before the drop-out,
  22.069, // THE BIG MOMENT: band slams back in (cut to landscape),
  44.138, // loudest stretch begins (-4.0 LUFS short-term),
  52.414, // cymbal wash / high sweep peak,
  57.242, // final heavy hits begin (pickup into bar 85),
  60.690, // release: the wall stops, song decays (window end)
];
const accentLabels = ["last full hit before the drop-out","THE BIG MOMENT: band slams back in (cut to landscape)","loudest stretch begins (-4.0 LUFS short-term)","cymbal wash / high sweep peak","final heavy hits begin (pickup into bar 85)","release: the wall stops, song decays (window end)"];

// fills: light-flicker moments. The riser's `hits` are grid-derived (32nd notes), the tom fill's are detected hits.
const fills = [
  { start: 21.379, end: 22.069, kind: "riser into the slam (not drums)", hits: [21.379,21.466,21.552,21.638,21.724,21.81,21.897,21.983] },
  { start: 23.451, end: 27.745, kind: "tom fill", hits: [23.451,23.627,23.967,24.14,24.477,25.155,25.333,25.506,25.85,26.03,26.204,26.389,26.726,26.898,27.573] },
];
const fillHits = fills.flatMap((f) => f.hits);

const sections = [
  { start: 0.000, end: 17.242, label: "BUILD - heavy 2-bar groove (store)" },
  { start: 17.242, end: 22.069, label: "DROP-OUT - bass+drums stop, riser (breath)" },
  { start: 22.069, end: 41.380, label: "CLIMAX - full-band wall slams in (landscape)" },
  { start: 41.380, end: 52.414, label: "LIFT/PEAK - bass thins, wall loudest" },
  { start: 52.414, end: 60.690, label: "FINAL HITS - cymbal wash, last heavy hits" },
];

const quiet = [
  { start: 17.242, end: 22.069, label: "drop-out, 5.5 s: only guitars/riser, no bass or kick" },
  { start: 41.380, end: 44.138, label: "bass thins for one bar before the peak" },
];

export const SLAM = downbeats[8]; // 22.069 — bar 9 "1": thumb presses play, full band slams in

// ---------- helpers (lists are sorted ascending; all O(log n)) ----------

// index of the last event <= t, or -1
export function lastIndex(t, list) {
  let lo = 0, hi = list.length - 1, r = -1;
  while (lo <= hi) {
    const m = (lo + hi) >> 1;
    if (list[m] <= t) { r = m; lo = m + 1; } else hi = m - 1;
  }
  return r;
}

// 0..1 envelope: jumps to (weight) at each event and decays exponentially (time constant `decay` s).
// Overlapping events take the max. `w` = optional weights array (e.g. weights.snares). Before the first event → 0.
export function pulse(t, list, decay = 0.12, w) {
  const i = lastIndex(t, list);
  let v = 0;
  for (let k = i; k >= 0 && k > i - 4; k--) {
    const dt = t - list[k];
    if (dt > decay * 8) break;
    v = Math.max(v, (w ? w[k] : 1) * Math.exp(-dt / decay));
  }
  return v;
}

// the event time nearest to t (number), or NaN for an empty list
export function nearest(t, list) {
  const i = nearestIndex(t, list);
  return i < 0 ? NaN : list[i];
}
export function nearestIndex(t, list) {
  if (!list.length) return -1;
  const i = lastIndex(t, list);
  if (i < 0) return 0;
  if (i >= list.length - 1) return list.length - 1;
  return t - list[i] <= list[i + 1] - t ? i : i + 1;
}

// seconds since the last event (Infinity before the first); number of events so far
export const since = (t, list) => { const i = lastIndex(t, list); return i < 0 ? Infinity : t - list[i]; };
export const count = (t, list) => lastIndex(t, list) + 1;

// { bar: 1..22, beat: 1..4, beatPhase: 0..1, barPhase: 0..1 } from the beat grid
export function beatInfo(t) {
  const b = Math.max(0, lastIndex(t, beats));
  const next = b + 1 < beats.length ? beats[b + 1] : beats[b] + BEAT;
  const beatPhase = Math.min(1, Math.max(0, (t - beats[b]) / (next - beats[b])));
  return { bar: Math.floor(b / 4) + 1, beat: (b % 4) + 1, beatPhase, barPhase: ((b % 4) + beatPhase) / 4 };
}

const spanAt = (t, spans) => spans.find((s) => t >= s.start && t < s.end) || null;
export const sectionAt = (t) => spanAt(t, sections);
export const quietAt = (t) => spanAt(t, quiet);
export const fillAt = (t) => spanAt(t, fills);

export default {
  WINDOW, BPM, BEAT, BAR, SIXTEENTH, SLAM,
  beats, downbeats, kicks, snares, hats, toms, weights,
  accents, accentLabels, fills, fillHits, sections, quiet,
  pulse, nearest, nearestIndex, lastIndex, since, count, beatInfo, sectionAt, quietAt, fillAt,
};
